name: Playwright Python BDD CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Playwright browsers
        run: |
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Run Behave BDD tests
        run: |
          behave
        env:
          # Set CI environment variable for headless mode
          CI: "1"
